/* ─────────────────────────────────────────────────────────────
 *  Vigil.OS — Seed data for initial registry
 *  Contains demo users (with hashed passwords), cases, documents,
 *  assets, shares, notifications, and audit trail.
 *
 *  Demo credentials:
 *    admin@vigil.os        / admin123
 *    investigator@vigil.os / invest123
 *    legal@vigil.os        / legal123
 *    court@vigil.os        / court123
 *    viewer@vigil.os       / viewer123
 * ───────────────────────────────────────────────────────────── */

import type { Registry } from "./dms-types";
import { hashPassword } from "./auth.server";
import { computeSha256 } from "./crypto.server";
import { saveLocalFile } from "./storage.server";

export async function buildSeedRegistry(): Promise<Registry> {
  // Pre-hash all demo passwords
  const [adminHash, investHash, legalHash, courtHash, viewerHash] =
    await Promise.all([
      hashPassword("admin123"),
      hashPassword("invest123"),
      hashPassword("legal123"),
      hashPassword("court123"),
      hashPassword("viewer123"),
    ]);

  const users: Registry["users"] = [
    {
      id: "usr-admin-001",
      name: "S. Rao",
      email: "admin@vigil.os",
      badge: "REC-0001",
      role: "ADMIN",
      passwordHash: adminHash,
      isActive: true,
      createdAt: "2024-01-15T08:00:00.000Z",
      lastLoginAt: "2024-10-25T09:00:00.000Z",
    },
    {
      id: "usr-invest-002",
      name: "Insp. A. Deshmukh",
      email: "investigator@vigil.os",
      badge: "MH-1180",
      role: "INVESTIGATOR",
      passwordHash: investHash,
      isActive: true,
      createdAt: "2024-02-10T09:30:00.000Z",
      lastLoginAt: "2024-10-24T16:30:00.000Z",
    },
    {
      id: "usr-legal-003",
      name: "Adv. K. Bhatia",
      email: "legal@vigil.os",
      badge: "PP-0092",
      role: "LEGAL_OFFICER",
      passwordHash: legalHash,
      isActive: true,
      createdAt: "2024-03-01T11:00:00.000Z",
      lastLoginAt: "2024-10-22T14:00:00.000Z",
    },
    {
      id: "usr-court-004",
      name: "R. Salvi",
      email: "court@vigil.os",
      badge: "MH-4471",
      role: "COURT_OFFICER",
      passwordHash: courtHash,
      isActive: true,
      createdAt: "2024-04-05T10:00:00.000Z",
      lastLoginAt: "2024-10-20T11:00:00.000Z",
    },
    {
      id: "usr-viewer-005",
      name: "Dr. N. Iyer",
      email: "viewer@vigil.os",
      badge: "FSL-303",
      role: "VIEWER",
      passwordHash: viewerHash,
      isActive: true,
      createdAt: "2024-05-12T14:00:00.000Z",
      lastLoginAt: "2024-10-18T10:00:00.000Z",
    },
  ];

  const doc = (
    id: string,
    caseId: string,
    refId: string,
    name: string,
    category: Registry["documents"][number]["category"],
    classification: Registry["documents"][number]["classification"],
    status: Registry["documents"][number]["status"],
    fallbackHash: string,
    uploadedBy: string,
    uploadedById: string,
    at: string,
    size: number,
    tags: string[] = [],
  ): Registry["documents"][number] => {
    const objectKey = `vigil/cases/${caseId}/${refId}-v1.0.0`;
    const originalName = `${refId}.pdf`;

    // Generate genuine PDF header and sealed dossier content
    const sampleContent = Buffer.from(
      `%PDF-1.4\n%Vigil.OS Cryptographic Dossier Record\n` +
      `Docket Reference: ${refId}\n` +
      `Title: ${name}\n` +
      `Category: ${category}\n` +
      `Classification: ${classification}\n` +
      `Case ID: ${caseId}\n` +
      `Sealed At: ${at}\n` +
      `Uploaded By: ${uploadedBy} (${uploadedById})\n` +
      `Security Protocol: SIH-26190 SHA-256 Cryptographic File Integrity Verification\n` +
      `Status: ${status}\n` +
      `%%EOF\n`
    );

    const computedHash = computeSha256(sampleContent);
    // Write physical file to local storage
    try {
      void saveLocalFile(objectKey, sampleContent);
    } catch {
      // safe fallback
    }

    const finalHash = computedHash || fallbackHash;

    return {
      id,
      caseId,
      refId,
      name,
      category,
      classification,
      status,
      currentVersion: "v1.0.0",
      versions: [
        {
          version: "v1.0.0",
          hash: finalHash,
          sha256_hash: finalHash,
          hash_algorithm: "SHA-256",
          hash_created_at: at,
          size: sampleContent.length || size,
          mimeType: "application/pdf",
          originalName,
          original_filename: originalName,
          stored_filename: `${refId}-v1.0.0.pdf`,
          uploadedAt: at,
          uploadedBy,
          uploadedById,
          objectKey,
          signature:
            status === "SIGNED"
              ? `SIG-${finalHash.slice(0, 12).toUpperCase()}`
              : null,
          signedBy: status === "SIGNED" ? uploadedBy : null,
          note: "Initial filing ingested into the archive with SHA-256 digest.",
          integrity_status: "VERIFIED",
          last_verified_at: at,
          verification_count: 1,
        },
      ],
      tags,
      sharedWith: ["INVESTIGATOR", "ADMIN"],
      updatedAt: at,
      createdAt: at,
      createdById: uploadedById,
      storage: "local",
    };
  };

  return {
    version: 1,
    users,
    cases: [
      {
        id: "case-8891",
        caseNumber: "2024-ND-8891",
        title: "Operation Silver Spoke — Racketeering Taskforce",
        summary:
          "Investigation into an illicit vehicle modification and parts-laundering ring operating across the northern industrial corridor.",
        status: "UNDER_INVESTIGATION",
        priority: "HIGH",
        classification: "CONFIDENTIAL",
        jurisdiction: "North District — Precinct 9",
        lead: "Insp. A. Deshmukh",
        leadId: "usr-invest-002",
        assignedOfficerIds: ["usr-invest-002", "usr-court-004"],
        openedAt: "2024-09-02T08:15:00.000Z",
        closedAt: null,
        statute: "IPC 420 / 120B",
        tags: ["racketeering", "vehicles", "taskforce"],
      },
      {
        id: "case-7712",
        caseNumber: "2024-CT-7712",
        title: "State vs. Vance — Commercial Larceny",
        summary:
          "Charge sheet filed for grand larceny at the Sector B commercial complex; matter listed for committal hearing.",
        status: "IN_TRIAL",
        priority: "MEDIUM",
        classification: "RESTRICTED",
        jurisdiction: "Sessions Court — Bench 4",
        lead: "Adv. K. Bhatia",
        leadId: "usr-legal-003",
        assignedOfficerIds: ["usr-legal-003", "usr-court-004"],
        openedAt: "2024-05-12T11:40:00.000Z",
        closedAt: null,
        statute: "IPC 379",
        tags: ["larceny", "trial"],
      },
      {
        id: "case-9920",
        caseNumber: "2024-FS-9920",
        title: "Encrypted Device Recovery — Device XJ",
        summary:
          "Forensic imaging and analysis of a recovered encrypted handset tied to the Silver Spoke network.",
        status: "OPEN",
        priority: "CRITICAL",
        classification: "TOP SECRET",
        jurisdiction: "Central Forensic Science Laboratory",
        lead: "Insp. A. Deshmukh",
        leadId: "usr-invest-002",
        assignedOfficerIds: ["usr-invest-002", "usr-viewer-005"],
        openedAt: "2024-10-18T06:05:00.000Z",
        closedAt: null,
        statute: "IT Act 65",
        tags: ["forensics", "digital", "encryption"],
      },
      {
        id: "case-5501",
        caseNumber: "2024-HM-5501",
        title: "Homicide Investigation — Riverside District",
        summary:
          "Murder investigation following discovery of remains near Riverside industrial area. Multiple witness statements recorded.",
        status: "UNDER_INVESTIGATION",
        priority: "CRITICAL",
        classification: "SECRET",
        jurisdiction: "East District — Precinct 3",
        lead: "Insp. A. Deshmukh",
        leadId: "usr-invest-002",
        assignedOfficerIds: ["usr-invest-002", "usr-legal-003"],
        openedAt: "2024-08-20T05:30:00.000Z",
        closedAt: null,
        statute: "IPC 302 / 201",
        tags: ["homicide", "forensics", "priority"],
      },
      {
        id: "case-3310",
        caseNumber: "2023-FR-3310",
        title: "Financial Fraud — Mercury Holdings",
        summary:
          "Investigation closed after successful prosecution. All evidence archived per court directive.",
        status: "CLOSED",
        priority: "LOW",
        classification: "RESTRICTED",
        jurisdiction: "Economic Offences Wing",
        lead: "Adv. K. Bhatia",
        leadId: "usr-legal-003",
        assignedOfficerIds: ["usr-legal-003"],
        openedAt: "2023-11-05T09:00:00.000Z",
        closedAt: "2024-06-15T16:00:00.000Z",
        statute: "IPC 420 / 468",
        tags: ["fraud", "financial", "closed"],
      },
    ],

    documents: [
      doc(
        "doc-fir-881",
        "case-8891",
        "FIR-881",
        "First Information Report — Precinct 9",
        "FIR",
        "CONFIDENTIAL",
        "SIGNED",
        "8f3a4c19d7b2e05fbb6712a4c9d0e77315ab2c4491ce0d6f2a3b4c5d6e7f8091ce",
        "Insp. A. Deshmukh",
        "usr-invest-002",
        "2024-09-02T09:12:02.000Z",
        482113,
        ["fir", "precinct-9"],
      ),
      doc(
        "doc-wns-004",
        "case-8891",
        "WNS-004",
        "Witness Statement — Alex R. (Redacted)",
        "Witness Statement",
        "SECRET",
        "SEALED",
        "d41c9f2b7a6e5d4c3b2a19087f6e5d4c3b2a1908f7e6d5c4b3a2190877712722f",
        "Insp. A. Deshmukh",
        "usr-invest-002",
        "2024-09-14T10:45:11.000Z",
        204880,
        ["witness", "redacted"],
      ),
      doc(
        "doc-fsc-992",
        "case-9920",
        "FSC-992",
        "Digital Forensics — Encrypted Device XJ",
        "Forensic Report",
        "TOP SECRET",
        "SIGNED",
        "44c1b8e2f90a3d7c5b1e6f4a2d8c0b9e7f5a3d1c8b6e4f2a0d9c7b5e3f1a44c1",
        "Dr. N. Iyer",
        "usr-viewer-005",
        "2024-10-24T09:12:02.000Z",
        1204990,
        ["forensics", "encrypted"],
      ),
      doc(
        "doc-chg-118",
        "case-7712",
        "CHG-118",
        "Preliminary Charge Sheet — State vs. Vance",
        "Charge Sheet",
        "RESTRICTED",
        "APPROVED",
        "91b4ac2077e3d1f5b8c6a4920d7e3f1b5a8c6d4e2f0b9a7c5d3e1f091b4ac20",
        "Adv. K. Bhatia",
        "usr-legal-003",
        "2024-06-01T08:30:00.000Z",
        318442,
        ["charge-sheet", "trial"],
      ),
      doc(
        "doc-crt-441",
        "case-7712",
        "CRT-441",
        "Court Filing — Committal Application",
        "Court Filing",
        "PUBLIC",
        "SIGNED",
        "3c12ff90ab77e4d2c1b0a9f8e7d6c5b4a3928170f6e5d4c3b2a190874e884e88",
        "R. Salvi",
        "usr-court-004",
        "2024-07-19T14:15:00.000Z",
        96004,
        ["court-filing", "committal"],
      ),
      doc(
        "doc-inv-550",
        "case-5501",
        "INV-550",
        "Investigation Record — Riverside Crime Scene",
        "Investigation Record",
        "SECRET",
        "UNDER_REVIEW",
        "a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7",
        "Insp. A. Deshmukh",
        "usr-invest-002",
        "2024-08-21T07:15:00.000Z",
        567890,
        ["crime-scene", "riverside"],
      ),
      doc(
        "doc-evd-551",
        "case-5501",
        "EVD-551",
        "Evidence Record — Physical Items Catalogue",
        "Evidence Record",
        "SECRET",
        "DRAFT",
        "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2",
        "Insp. A. Deshmukh",
        "usr-invest-002",
        "2024-08-22T10:30:00.000Z",
        234567,
        ["evidence", "physical"],
      ),
      doc(
        "doc-lgl-331",
        "case-3310",
        "LGL-331",
        "Legal Notice — Mercury Holdings",
        "Legal Notice",
        "RESTRICTED",
        "ARCHIVED",
        "c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3",
        "Adv. K. Bhatia",
        "usr-legal-003",
        "2023-12-01T09:00:00.000Z",
        145200,
        ["legal-notice", "fraud"],
      ),
      doc(
        "doc-jdg-332",
        "case-3310",
        "JDG-332",
        "Judgment — Mercury Holdings Fraud Case",
        "Judgment",
        "PUBLIC",
        "SIGNED",
        "d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4",
        "R. Salvi",
        "usr-court-004",
        "2024-06-15T15:00:00.000Z",
        890123,
        ["judgment", "final"],
      ),
      doc(
        "doc-pr-882",
        "case-8891",
        "PR-882",
        "Police Report — Surveillance Log",
        "Police Report",
        "CONFIDENTIAL",
        "SEALED",
        "e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5",
        "R. Salvi",
        "usr-court-004",
        "2024-09-10T16:00:00.000Z",
        312000,
        ["surveillance", "report"],
      ),
    ],

    assets: [
      {
        id: "asset-tr-442",
        tag: "TR-882",
        name: "Tactical Radio Hub #442",
        category: "RADIO",
        serial: "88-129-99-X",
        status: "ISSUED",
        assignedTo: "Dr. N. Iyer",
        station: "Precinct 9",
        acquiredAt: "2022-03-11T00:00:00.000Z",
        lastServiceAt: "2024-08-15T00:00:00.000Z",
        serviceIntervalDays: 180,
        linkedCaseId: "case-9920",
        events: [
          {
            at: "2022-03-11T00:00:00.000Z",
            action: "ACQUIRED",
            actor: "Stores",
            note: "Procured under tender 2022/RD/14.",
          },
          {
            at: "2024-08-15T00:00:00.000Z",
            action: "SERVICED",
            actor: "Signals Wing",
            note: "Firmware and battery pack replaced.",
          },
          {
            at: "2024-10-02T00:00:00.000Z",
            action: "ISSUED",
            actor: "Stores",
            note: "Issued to Dr. N. Iyer for field imaging.",
          },
        ],
      },
      {
        id: "asset-vhc-b12",
        tag: "V-901",
        name: "Interception Unit — B12",
        category: "VEHICLE",
        serial: "1HG-CM-192",
        status: "MAINTENANCE",
        assignedTo: "Patrol Unit 4",
        station: "North District Motor Pool",
        acquiredAt: "2021-11-02T00:00:00.000Z",
        lastServiceAt: "2024-10-02T00:00:00.000Z",
        serviceIntervalDays: 120,
        linkedCaseId: null,
        events: [
          {
            at: "2021-11-02T00:00:00.000Z",
            action: "ACQUIRED",
            actor: "Motor Pool",
            note: "Inducted into interception fleet.",
          },
          {
            at: "2024-10-02T00:00:00.000Z",
            action: "MAINTENANCE",
            actor: "Motor Pool",
            note: "Suspension fault reported after pursuit.",
          },
        ],
      },
      {
        id: "asset-wpn-4921",
        tag: "WPN-G17",
        name: "Service Pistol Glock 17 Gen 5",
        category: "WEAPON",
        serial: "G17-4921",
        status: "IN_SERVICE",
        assignedTo: "R. Salvi",
        station: "Precinct 9 Armoury",
        acquiredAt: "2023-01-19T00:00:00.000Z",
        lastServiceAt: "2024-08-15T00:00:00.000Z",
        serviceIntervalDays: 365,
        linkedCaseId: null,
        events: [
          {
            at: "2023-01-19T00:00:00.000Z",
            action: "ACQUIRED",
            actor: "Armoury",
            note: "Armoury induction and ballistic sampling.",
          },
          {
            at: "2024-08-15T00:00:00.000Z",
            action: "SERVICED",
            actor: "Armoury",
            note: "Annual inspection cleared.",
          },
        ],
      },
      {
        id: "asset-dvc-7712",
        tag: "DVC-TB",
        name: "Forensic Tablet — Field Imaging",
        category: "DEVICE",
        serial: "TB-7712",
        status: "RETIRED",
        assignedTo: "Evidence Lab",
        station: "Central Forensic Science Laboratory",
        acquiredAt: "2019-04-08T00:00:00.000Z",
        lastServiceAt: "2023-12-19T00:00:00.000Z",
        serviceIntervalDays: 240,
        linkedCaseId: null,
        events: [
          {
            at: "2019-04-08T00:00:00.000Z",
            action: "ACQUIRED",
            actor: "Stores",
            note: "Purchased for field imaging duty.",
          },
          {
            at: "2023-12-19T00:00:00.000Z",
            action: "RETIRED",
            actor: "Lab Custodian",
            note: "End of life; data sanitised and certified.",
          },
        ],
      },
    ],

    shares: [
      {
        id: "share-001",
        documentId: "doc-chg-118",
        sharedByUserId: "usr-legal-003",
        sharedByName: "Adv. K. Bhatia",
        sharedWithUserId: "usr-court-004",
        sharedWithName: "R. Salvi",
        permissions: ["VIEW", "DOWNLOAD"],
        expiresAt: "2025-01-01T00:00:00.000Z",
        createdAt: "2024-10-20T11:00:00.000Z",
        isActive: true,
      },
      {
        id: "share-002",
        documentId: "doc-fir-881",
        sharedByUserId: "usr-invest-002",
        sharedByName: "Insp. A. Deshmukh",
        sharedWithUserId: "usr-legal-003",
        sharedWithName: "Adv. K. Bhatia",
        permissions: ["VIEW"],
        expiresAt: null,
        createdAt: "2024-09-05T14:00:00.000Z",
        isActive: true,
      },
    ],

    notifications: [
      {
        id: "notif-001",
        userId: "usr-invest-002",
        type: "DOCUMENT_UPLOADED",
        title: "New forensic report filed",
        message:
          "Dr. N. Iyer uploaded Digital Forensics — Encrypted Device XJ to case 2024-FS-9920.",
        isRead: false,
        createdAt: "2024-10-24T09:12:02.000Z",
        linkedEntityId: "doc-fsc-992",
        linkedEntityType: "document",
      },
      {
        id: "notif-002",
        userId: "usr-court-004",
        type: "DOCUMENT_SHARED",
        title: "Document shared with you",
        message:
          "Adv. K. Bhatia shared Preliminary Charge Sheet — State vs. Vance with you.",
        isRead: false,
        createdAt: "2024-10-20T11:00:00.000Z",
        linkedEntityId: "doc-chg-118",
        linkedEntityType: "document",
      },
      {
        id: "notif-003",
        userId: "usr-legal-003",
        type: "REVIEW_REQUESTED",
        title: "Review requested",
        message:
          "Investigation Record — Riverside Crime Scene is pending your review.",
        isRead: true,
        createdAt: "2024-08-21T07:30:00.000Z",
        linkedEntityId: "doc-inv-550",
        linkedEntityType: "document",
      },
      {
        id: "notif-004",
        userId: "usr-admin-001",
        type: "TAMPER_DETECTED",
        title: "Tamper alert",
        message:
          "Integrity check failed for a document. Please review the audit trail.",
        isRead: false,
        createdAt: "2024-10-25T08:00:00.000Z",
        linkedEntityId: null,
        linkedEntityType: null,
      },
      {
        id: "notif-005",
        userId: "usr-invest-002",
        type: "CASE_ASSIGNED",
        title: "New case assignment",
        message: "You have been assigned to Homicide Investigation — Riverside District.",
        isRead: true,
        createdAt: "2024-08-20T06:00:00.000Z",
        linkedEntityId: "case-5501",
        linkedEntityType: "case",
      },
    ],

    audit: [
      {
        id: "aud-0001",
        at: "2024-10-25T09:00:00.000Z",
        actor: "S. Rao",
        actorId: "usr-admin-001",
        role: "ADMIN",
        action: "USER_LOGIN",
        target: "admin@vigil.os",
        targetId: "usr-admin-001",
        detail: "Authenticated successfully.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0002",
        at: "2024-10-24T09:12:02.000Z",
        actor: "Dr. N. Iyer",
        actorId: "usr-viewer-005",
        role: "VIEWER",
        action: "DOCUMENT_UPLOADED",
        target: "Digital Forensics — Encrypted Device XJ",
        targetId: "doc-fsc-992",
        detail: "Document hash finalised on ingest.",
        hash: "44c1b8e2f90a3d7c5b1e6f4a2d8c0b9e7f5a3d1c8b6e4f2a0d9c7b5e3f1a44c1",
        ipAddress: null,
      },
      {
        id: "aud-0003",
        at: "2024-10-24T09:12:14.000Z",
        actor: "System",
        actorId: "system",
        role: "ADMIN",
        action: "INTEGRITY_VERIFIED",
        target: "Digital Forensics — Encrypted Device XJ",
        targetId: "doc-fsc-992",
        detail: "Automated hash verification complete — chain intact.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0004",
        at: "2024-10-24T10:45:11.000Z",
        actor: "Insp. A. Deshmukh",
        actorId: "usr-invest-002",
        role: "INVESTIGATOR",
        action: "DOCUMENT_VIEWED",
        target: "Witness Statement — Alex R. (Redacted)",
        targetId: "doc-wns-004",
        detail: "Contents confirmed as matching the FIR narrative.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0005",
        at: "2024-10-24T11:05:59.000Z",
        actor: "S. Rao",
        actorId: "usr-admin-001",
        role: "ADMIN",
        action: "ACCESS_GRANTED",
        target: "Preliminary Charge Sheet — State vs. Vance",
        targetId: "doc-chg-118",
        detail: "Legal Officer cadre granted read-only access.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0006",
        at: "2024-10-24T14:40:02.000Z",
        actor: "S. Rao",
        actorId: "usr-admin-001",
        role: "ADMIN",
        action: "CLASSIFICATION_CHANGED",
        target: "Court Filing — Committal Application",
        targetId: "doc-crt-441",
        detail: "Record moved from RESTRICTED to PUBLIC after listing.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0007",
        at: "2024-10-20T11:00:00.000Z",
        actor: "Adv. K. Bhatia",
        actorId: "usr-legal-003",
        role: "LEGAL_OFFICER",
        action: "DOCUMENT_SHARED",
        target: "Preliminary Charge Sheet — State vs. Vance",
        targetId: "doc-chg-118",
        detail: "Shared with R. Salvi (VIEW + DOWNLOAD).",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0008",
        at: "2024-09-14T10:45:11.000Z",
        actor: "Insp. A. Deshmukh",
        actorId: "usr-invest-002",
        role: "INVESTIGATOR",
        action: "DOCUMENT_UPLOADED",
        target: "Witness Statement — Alex R. (Redacted)",
        targetId: "doc-wns-004",
        detail: "Witness statement sealed with SHA-256 digest.",
        hash: "d41c9f2b7a6e5d4c3b2a19087f6e5d4c3b2a1908f7e6d5c4b3a2190877712722f",
        ipAddress: null,
      },
      {
        id: "aud-0009",
        at: "2024-09-02T09:12:02.000Z",
        actor: "Insp. A. Deshmukh",
        actorId: "usr-invest-002",
        role: "INVESTIGATOR",
        action: "CASE_CREATED",
        target: "Operation Silver Spoke — Racketeering Taskforce",
        targetId: "case-8891",
        detail: "Dossier opened under IPC 420 / 120B.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0010",
        at: "2024-08-21T07:15:00.000Z",
        actor: "Insp. A. Deshmukh",
        actorId: "usr-invest-002",
        role: "INVESTIGATOR",
        action: "WORKFLOW_CHANGED",
        target: "Investigation Record — Riverside Crime Scene",
        targetId: "doc-inv-550",
        detail: "Status changed from DRAFT to UNDER_REVIEW.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0011",
        at: "2024-08-20T05:30:00.000Z",
        actor: "Insp. A. Deshmukh",
        actorId: "usr-invest-002",
        role: "INVESTIGATOR",
        action: "CASE_CREATED",
        target: "Homicide Investigation — Riverside District",
        targetId: "case-5501",
        detail: "Dossier opened under IPC 302 / 201.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0012",
        at: "2024-06-15T16:00:00.000Z",
        actor: "Adv. K. Bhatia",
        actorId: "usr-legal-003",
        role: "LEGAL_OFFICER",
        action: "CASE_CLOSED",
        target: "Financial Fraud — Mercury Holdings",
        targetId: "case-3310",
        detail: "Case closed after successful prosecution.",
        hash: null,
        ipAddress: null,
      },
      {
        id: "aud-0013",
        at: "2024-06-15T15:00:00.000Z",
        actor: "R. Salvi",
        actorId: "usr-court-004",
        role: "COURT_OFFICER",
        action: "DOCUMENT_SIGNED",
        target: "Judgment — Mercury Holdings Fraud Case",
        targetId: "doc-jdg-332",
        detail: "Digitally signed v1.0.0.",
        hash: "d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4",
        ipAddress: null,
      },
      {
        id: "aud-0014",
        at: "2024-06-01T08:30:00.000Z",
        actor: "Adv. K. Bhatia",
        actorId: "usr-legal-003",
        role: "LEGAL_OFFICER",
        action: "DOCUMENT_UPLOADED",
        target: "Preliminary Charge Sheet — State vs. Vance",
        targetId: "doc-chg-118",
        detail: "Charge sheet ingested and sealed.",
        hash: "91b4ac2077e3d1f5b8c6a4920d7e3f1b5a8c6d4e2f0b9a7c5d3e1f091b4ac20",
        ipAddress: null,
      },
      {
        id: "aud-0015",
        at: "2024-02-10T09:30:00.000Z",
        actor: "S. Rao",
        actorId: "usr-admin-001",
        role: "ADMIN",
        action: "USER_CREATED",
        target: "Insp. A. Deshmukh",
        targetId: "usr-invest-002",
        detail: "New INVESTIGATOR account created for investigator@vigil.os.",
        hash: null,
        ipAddress: null,
      },
    ],
  };
}
